- name: onyx_upgrade
#  hosts: ONYX:&{{limit_hosts}}
  hosts: ONYX
  gather_facts: no
  strategy: free
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    #local_path: "/mswg/release/sx_mlnx_os/"
    cpu: "X86_64"   # X86_64 | PPC_M460EX
    force_upgrade_downgrade: "False"
    #version: 3.8.2204
    skip_version_check: "False"
    fetch: "True"
    transfer_protocol: scp
    server_ip: ""
    server_user: ""
    server_password: ""
    img_file: ""
    #source_file1: "{{local_path}}/sx_mlnx_os-{{ version }}/{{ cpu  }}/image-{{ cpu }}-{{ version }}.img"
    #source_file2: "{{local_path}}/image-{{ cpu }}-{{ version }}.img"
    destination_folder: /var/opt/tms/images/
    reload: True
    ignore_net_errors: "True"
  remote_user: admin
  tasks:

# get current switch Onyx version with command "show version concise" and save it to a variable named curr_version

    - name: get_current_switch_version
      onyx_command:
        commands: show version concise
      register: curr_version
# save the onyx version as a fact named current_version
    - name: set_fact_current_version
      set_fact:
        current_version: "{{curr_version.stdout[0].split()[1] }}"
# print the current version
    - name: print_current_version
      debug:
          msg: "Current version: {{ current_version }}"

# in case current version is not the same as the needed version - start the upgrade
    - name: check_file_exists
      stat:
        path: "{{ img_file }}"
      delegate_to: localhost
      register: file_exists

    - name: get_file_basename
      set_fact:
        img_name: "{{ img_file | basename }}"
      when:
         - file_exists.stat.exists
    - name: file_doesnt_exists
      debug:
        msg: "file {{img_file}} doesnt exist"
      when:
         - file_exists.stat.exists == False

  # Copy image file to the switch using the net_put module using scp
    - name: need_to_upgrade
      block:
        - name: get_file_basename
          set_fact:
            img_name: "{{ img_file | basename }}"
          when:
             - file_exists.stat.exists

        - name: copy_file_to_device
          net_put:
              dest: "{{ destination_folder }}"
              mode: binary
              protocol: "{{ transfer_protocol }}"
              src: "{{ img_file }}"
          tags: copy_to_onyx
          ignore_errors: yes
          when:
           - file_exists.stat.exists
           - ignore_net_errors == "True"
           - fetch != "True"
     # fetch the image file using a cli command
        - name: fetch_image
          onyx_command:
              commands: image fetch {{transfer_protocol}}://{{server_user}}:{{server_password}}@{{server_ip}}://{{img_file}}
          tags: fetch_image
          when:
               - file_exists.stat.exists
               - ignore_net_errors == "True"
               - fetch == "True"


     #  install the image
        - name: image install
          onyx_command:
               commands: image install {{ img_file | basename }}
          tags: image_install

      # image boot next + save config + no boot next fallback-reboot enable in case  force_upgrade_downgrade == True
        - name: image boot next and reload with upgrade_downgrade_force
          onyx_config:
                lines:
                  - image boot next
                  - configuration write
                  - no boot next fallback-reboot enable
                backup: yes
          when:
             - force_upgrade_downgrade == "True"
          ignore_errors: yes
          tags: boot_next

      # image boot next + save config
        - name: image boot next and reload without upgrade_downgrade_force
          onyx_config:
                lines:
                  - image boot next
                  - configuration write
                backup: yes
          when:
              - force_upgrade_downgrade != "True"
          tags: boot_next

      # run the reload command, need to set ignore errors to yes since the ssh is broken with the reload command
        - name: reload
          onyx_config:
                commands:
                    - reload
          when: reload == True
          ignore_errors: yes
          tags: reload

            # use wait_for to wait for port 22 to be available on the switch after reboot
        - name: wait for switch to reboot
          delegate_to: localhost
          wait_for:
             host: "{{ inventory_hostname }}"
             port: 22
             delay: 360
             timeout: 800
          become: false
          tags: wait_for_ssh

          # wait for full cli to be availble by waiting for output of "show version concise" to have the new version
        - name: wait_for_switch_cli
          onyx_command:
            commands: show version concise
            wait_for:
              - result[0] contains x86_64
          tags: wait_for_switch_cli
          register: new_version

          # print the new version after reboot
        - name: print_new_version
          debug:
            msg: "New version after upgrade: {{new_version.stdout}}"
          tags: print_new_version
      when:
        - file_exists.stat.exists
